### ISSUE TITLE
源码安装依赖报错 No matching version found for @widget-js/core@* inside the workspace

### ISSUE THREAD

**Issue by anchuanyuan** [widget-js/widgets#12]
当我clone源码以后 安装依赖会报如下的错误

 ERR_PNPM_NO_MATCHING_VERSION_INSIDE_WORKSPACE  In : No matching version found for @widget-js/core@* inside the workspace

**Comment by anchuanyuan** [comment]
我把 @widget-js/vite-plugin-widget 固定成1.0.1能安装依赖了 1.0.2的可能有问题 但是我不知道问题在哪

**Comment by singgg** [comment]
![image](https://user-images.githubusercontent.com/24663140/233058670-ac5c2509-13fd-4899-b61a-2d011eb9ee77.png)

这个是什么问题吗？

**Comment by rtugeek** [comment]
> ![image](https://user-images.githubusercontent.com/24663140/233058670-ac5c2509-13fd-4899-b61a-2d011eb9ee77.png)
> 
> 这个是什么问题吗？

把package.json的 @widget-js/vite-plugin-widget版本改成 1.0.4：

```
"@widget-js/vite-plugin-widget": "^1.0.3"
=>
"@widget-js/vite-plugin-widget": "^1.0.4"

```

**Comment by singgg** [comment]
![image](https://user-images.githubusercontent.com/24663140/233091891-646e5bb1-c312-418a-aa81-9a320e165fb2.png)

vue3组件也是需要修复吧

**Comment by rtugeek** [comment]
> ![image](https://user-images.githubusercontent.com/24663140/233091891-646e5bb1-c312-418a-aa81-9a320e165fb2.png)
> 
> vue3组件也是需要修复吧 @rtugeek

改成这个 @widget-js/vue3@0.1.27

**Comment by x1ntt** [comment]
@rtugeek 

取现在最新的代码会有如下错误
```shell
D:\1\widgets>pnpm install
 WARN  deprecated eslint@8.48.0: This version is no longer supported. Please see https://eslint.org/version-support for other options.
 WARN  deprecated @lobehub/icons@1.98.0: deprecate
 ERR_PNPM_WORKSPACE_PKG_NOT_FOUND  In : "@widget-js/core@workspace:*" is in the dependencies but no package named "@widget-js/core" is present in the workspace

This error happened while installing a direct dependency of D:\1\widgets

Packages found in the workspace:
Progress: resolved 54, reused 54, downloaded 0, added 0
```
应该如何修改？

当我按照上述修改版本后，得到如下错误，是否是版本号有变动导致的
```shell
D:\1\widgets>pnpm serve

> @widget-js/widgets@0.0.1 serve D:\1\widgets
> vite

i root: D:/1/widgets                                                                                          18:14:27
error when starting dev server:
evalmachine.<anonymous>:14
const SitReminderWidgetDefine = new core_1.BackgroundWidget({
                                ^

TypeError: core_1.BackgroundWidget is not a constructor
    at evalmachine.<anonymous>:14:33
    at Script.runInContext (node:vm:149:12)
    at Script.runInNewContext (node:vm:154:17)
    at Object.runInNewContext (node:vm:310:38)
    at transpileCode (D:\1\widgets\node_modules\.pnpm\@widget-js+utils@0.10.21\node_modules\@widget-js\utils\dist\index.js:57:28)
    at scanWidgets (file:///D:/1/widgets/node_modules/.pnpm/@widget-js+vite-plugin-widg_ea604f935530371cfe5ac7259d776f4b/node_modules/@widget-js/vite-plugin-widget/dist/index.mjs:24:21)
    at async scanPackage (file:///D:/1/widgets/node_modules/.pnpm/@widget-js+vite-plugin-widg_ea604f935530371cfe5ac7259d776f4b/node_modules/@widget-js/vite-plugin-widget/dist/index.mjs:44:21)
    at async generateWidgetPackageJson (file:///D:/1/widgets/node_modules/.pnpm/@widget-js+vite-plugin-widg_ea604f935530371cfe5ac7259d776f4b/node_modules/@widget-js/vite-plugin-widget/dist/index.mjs:106:27)
    at async configResolved (file:///D:/1/widgets/node_modules/.pnpm/@widget-js+vite-plugin-widg_ea604f935530371cfe5ac7259d776f4b/node_modules/@widget-js/vite-plugin-widget/dist/index.mjs:139:9)
    at async Promise.all (index 6)
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by x1ntt** [comment]
目前修改配置
```shell
    "@widget-js/core": "latest",
    "@widget-js/vue3": "latest",
```
好使
